### ISSUE TITLE
how can i set the offset

### ISSUE THREAD

**Issue by zhjygit** [vykt/libpwu#1]
simple_hook:
![image](https://github.com/vykt/libpwu/assets/44870751/7b4f5dde-cce9-4af6-9472-b4affa92f5d2)

simple_resolve:
![image](https://github.com/vykt/libpwu/assets/44870751/89937a8a-a87a-42b3-b2cc-696c13c5126f)
how can i debug it, printf("xxx") (&n_pid, &target_pid),print the pid?

new_thread:
 unsigned int thread_work_offset = 0x7fe
how can i set the offset? why is 0x7fe

**Comment by vykt** [comment]
### First, your questions:

In this example, the process ID is stored in `target_pid`. To print its value you can insert the following line after the call to `pid_by_name()`:
```
printf("target pid: %d\n", target_pid);
```

<br>

The `thread_work_offset` is the offset into the .text segment where the function we want our thread to run is located. You find this offset by reverse engineering the target executable. We need to use offsets instead of absolute addresses because of ASLR.


### Some notes:

To debug the code itself I would suggest using gdb. With gdb you can step through the program a line at a time and print any of the variables as the need arises. This is a lot more flexible than using print statements and will probably become necessary should the programs you work on exceed the scale of this example.

To see whether the program correctly writes to memory, I would suggest using something like radare2 and opening `/proc/[pid]/mem` and seeking to the address where you expect the writes to take place.
